(function(){
'use strict';
const $=id=>document.getElementById(id),fmt=n=>String(Number(n)).padStart(2,'0'),money=v=>Number(v||0).toLocaleString('ru-RU')+' ₽';
const URL='data/xray-runtime.json';let runtime=null,payouts=null,refreshing=null,refreshError='',lastGen='',panel={grid:true,combos:true,fact:true,archive:false,payouts:false};
async function fetchJSON(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'ts='+Date.now(),{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()}
async function loadPayouts(){if(!payouts)payouts=await fetchJSON('keno-payouts-v1.json');return payouts}

function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function savedPayout(e,branch){const legacy=branch==='5A'?'combo5Payout':branch==='7A'?'combo7Payout':null;return Number(e['combo'+branch+'Payout']??(legacy?e[legacy]:0)??0)}
function savedTotal(e){return e.totalPayout!=null?Number(e.totalPayout):['5A','5B','7A','7B'].reduce((s,k)=>s+savedPayout(e,k),0)}
function eligibilityHTML(e){const reasons=[];if(e.lateForecast)reasons.push('создан после времени тиража');if(e.replacedForecast)reasons.push('прогноз заменялся');if(e.statisticsEligible===false&&!reasons.length)reasons.push('время публикации не подтверждено');return reasons.length?'<div class="xrayIntegrityNote">Исключён из честной статистики: '+reasons.join('; ')+'. Результат сохранён для аудита.</div>':''}
function diagnosticsHTML(f){if(!f)return '';return '<details class="xrayDiagnostics"><summary>Данные frozen-прогноза</summary><div>Движок: '+escapeHTML(f.engineVersion||f.version||'—')+'</div><div>Создан: '+escapeHTML(f.createdAt||'—')+'</div><div>Источник: №'+escapeHTML(f.sourceDraw)+' → цель: №'+escapeHTML(f.targetDraw)+'</div><div>Fingerprint: <code>'+escapeHTML(f.forecastFingerprint||'legacy: ещё не присвоен')+'</code></div></details>'}
function runtimeNotice(){const a=runtime?.anomaly;const missing=a?.code==='MISSING_TARGET_FACT',missed=a?.code==='MISSED_FORECAST_WINDOW';const error=a?'<div class="xrayRuntimeError" role="alert"><b>Автоматическое продвижение XRAY остановлено</b><div>'+escapeHTML(a.code)+'</div><div>'+(missing?'В архиве отсутствует целевой факт №'+escapeHTML(a.targetDraw)+'. Frozen-прогноз сохранён.':missed?'Окно создания прогноза пропущено. Требуется проверка истории перед продолжением.':'Требуется проверка runtime.')+'</div></div>':'';return error+(refreshError?'<div class="xrayRuntimeError" role="status">Обновление недоступно. '+(runtime?'Показаны последние успешно загруженные данные. ':'')+escapeHTML(refreshError)+'</div>':'')}
let overlayFrame=0,resizeObserver=null,visibilityObserver=null;
function scheduleOverlay(){if(overlayFrame)return;overlayFrame=requestAnimationFrame(()=>{overlayFrame=0;renderOverlay(runtime?.forecast)})}
function watchLayout(){resizeObserver?.disconnect();if(typeof ResizeObserver==='function'){resizeObserver??=new ResizeObserver(scheduleOverlay);for(const el of [$('xrayRoot'),$('xrayStage')])if(el)resizeObserver.observe(el)}visibilityObserver?.disconnect();if(typeof MutationObserver==='function'&&$('xray')){visibilityObserver??=new MutationObserver(scheduleOverlay);visibilityObserver.observe($('xray'),{attributes:true,attributeFilter:['class','style','hidden']})}}

function head(title,key,extra=''){return `<div class="xrayPanelHead"><div><b>${title}</b>${extra?`<small>${extra}</small>`:''}</div><button class="xrayFold ${panel[key]?'on':''}" data-xfold="${key}" type="button">▼</button></div>`}
function targetLabel(x){return `№${x?.targetDraw||'—'} · ${x?.targetDate||'—'} ${x?.targetTime||'—'}`}
function sourceLabel(x){return `№${x?.sourceDraw||'—'} · ${x?.sourceDate||'—'} ${x?.sourceTime||'—'}${x?.sourceColumn?` · столб ${x.sourceColumn}`:''}`}
function relationClass(s){return String(s||'').toLowerCase().replace('column','root')}
function gridHTML(f){
 const fact=new Set((f?.current20||runtime?.latestOfficial?.balls||[]).map(Number)),pred=new Set((f?.predicted20||[]).map(Number)),nei=new Set((f?.structure?.neighborFront||[]).map(Number));let out='';
 for(let level=0;level<9;level++)for(let c=1;c<=9;c++){const n=level*9+c;if(n>80){out+='<span class="xrayCell blank"></span>';continue}const cls=fact.has(n)&&pred.has(n)?'both':fact.has(n)?'current':pred.has(n)?'predicted':nei.has(n)?'neighbor':'';out+=`<button class="xrayCell ${cls}" type="button" data-xcell="${n}" title="Ст${c} · L${level}">${n}</button>`}
 return out;
}
function concentrationLabels(){return `<div class="xrayColHeads">${Array.from({length:9},(_,i)=>`<b>Ст${i+1}</b>`).join('')}</div>`}
function renderOverlay(f){const svg=$('xrayOverlay'),stage=$('xrayStage');if(!svg||!stage)return;svg.replaceChildren();if(!f)return;const rect=stage.getBoundingClientRect();if(rect.width<=0||rect.height<=0||stage.getClientRects().length===0){svg.removeAttribute('viewBox');return}svg.setAttribute('viewBox',`0 0 ${rect.width} ${rect.height}`);const colors={asc:'#57db77',draw:'#56baff',root:'#ffd34d',vortex:'#d98cff',level:'#ff8e5d'},ns='http://www.w3.org/2000/svg',defs=document.createElementNS(ns,'defs');for(const [type,color] of Object.entries(colors)){const marker=document.createElementNS(ns,'marker'),path=document.createElementNS(ns,'path');for(const [key,value] of Object.entries({id:'xrayArrow-'+type,markerWidth:7,markerHeight:7,refX:6,refY:3.5,orient:'auto'}))marker.setAttribute(key,value);path.setAttribute('d','M0,0 L7,3.5 L0,7 z');path.setAttribute('fill',color);marker.appendChild(path);defs.appendChild(marker)}svg.appendChild(defs);for(const e of (f.movementEdges||[]).slice(0,10)){const type=relationClass(e.type);if(!colors[type])continue;const a=stage.querySelector('[data-xcell="'+Number(e.from)+'"]'),b=stage.querySelector('[data-xcell="'+Number(e.to)+'"]');if(!a||!b)continue;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();if(!ar.width||!ar.height||!br.width||!br.height)continue;const line=document.createElementNS(ns,'line');line.setAttribute('x1',ar.left+ar.width/2-rect.left);line.setAttribute('y1',ar.top+ar.height/2-rect.top);line.setAttribute('x2',br.left+br.width/2-rect.left);line.setAttribute('y2',br.top+br.height/2-rect.top);line.setAttribute('class','xrayArrowLine rel-'+type);line.setAttribute('marker-end','url(#xrayArrow-'+type+')');svg.appendChild(line)}}
function activityTable(rows,type){if(!rows?.length)return '';const label=type==='column'?'Ст':'L',key=type==='column'?'column':'level';return `<div class="xrayMoveTableWrap"><table class="xrayMoveTable"><thead><tr><th>${label}</th><th>T1</th><th>T2</th><th>T5</th><th>T10</th><th>T20</th><th>1→2</th><th>2→5</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${label}${r[key]}</th><td>${r.t1}</td><td>${r.t2}</td><td>${r.t5}</td><td>${r.t10}</td><td>${r.t20}</td><td class="${r.d12>0?'up':r.d12<0?'down':''}">${r.d12>0?'+':''}${r.d12}</td><td class="${r.d25>0?'up':r.d25<0?'down':''}">${r.d25>0?'+':''}${r.d25}</td></tr>`).join('')}</tbody></table></div>`}
function structureHTML(f){const s=f?.structure;if(!s)return '';const asc=(s.adjacency?.ascTop||[]).slice(0,7),draw=(s.adjacency?.drawTop||[]).slice(0,7),edges=(f.movementEdges||[]).slice(0,10);return `<div class="xrayStructureBox"><div class="xrayStructureTitle"><b>Движение таблицы</b><span>без общего рейтинга · T1/T2/T5/T10/T20</span></div><div class="xrayRankLine"><b>Столбы концентрации:</b> ${(s.columnRank||[]).map(x=>`Ст${x}`).join(' → ')}</div><div class="xrayRankLine"><b>LEVEL:</b> ${(s.levelRank||[]).map(x=>`L${x}`).join(' → ')}</div><details><summary>Активность столбов концентрации</summary>${activityTable(s.concentrationColumns,'column')}</details><details><summary>Активность LEVEL</summary>${activityTable(s.levelRows,'level')}</details><div class="xrayNeighborGrid"><div><b>➡️ По возрастанию ASC</b>${asc.map(x=>`<span>${fmt(x.from)}–${fmt(x.to)} · ${x.strength.toFixed(2)}</span>`).join('')}</div><div><b>🎲 По выпадению DRAW</b>${draw.map(x=>`<span>${fmt(x.from)}→${fmt(x.to)} · ${x.strength.toFixed(2)}</span>`).join('')}</div></div><div class="xrayVortex"><b>Vortex / Tesla:</b> 1→2→4→8→7→5→1 &nbsp; · &nbsp; 3↔6 &nbsp; · &nbsp; 9</div><div class="xrayActualMoves"><b>Связи поддержки прогнозных 20</b>${edges.length?edges.map(e=>`<span class="rel-${relationClass(e.type)}">${fmt(e.from)}→${fmt(e.to)} · ${e.type}${e.strength?` ${e.strength.toFixed(2)}`:''}</span>`).join(''):'<small>Нет связей для отображения.</small>'}</div></div>`}
function nums20(nums,hits=null,mode='pending'){const H=hits?new Set(hits.map(Number)):null;return `<div class="xray20Nums">${(nums||[]).map(n=>`<span class="${H?(H.has(Number(n))?'hit':'miss'):mode}">${fmt(n)}</span>`).join('')}</div>`}
function comboRow(label,nums,hits=null,payout=0){const H=hits?new Set(hits.map(Number)):null;return `<div class="xrayComboRow"><b>${label}</b><div class="xrayComboRowNums">${(nums||[]).map(n=>`<span class="${H?(H.has(Number(n))?'hit':'miss'):'pending'}">${fmt(n)}${H?(H.has(Number(n))?'✓':'×'):''}</span>`).join('')}</div>${H?`<strong class="xrayWin">${money(payout)}</strong>`:''}</div>`}
function comboPanel(title,cls,nums,subtitle){return `<div class="xrayCombo ${cls}"><div class="xrayComboTop"><b>${title}</b><span>${subtitle}</span></div><div class="xrayComboNums">${(nums||[]).map(n=>`<span>${fmt(n)}</span>`).join('')}</div></div>`}
function forecastBlock(f){if(!f)return '<div class="msg">Жду следующий frozen-прогноз.</div>';return `<div class="xrayForecast20"><div class="xrayForecastTitle"><b>FROZEN-прогноз · 20 чисел</b><span>на ${targetLabel(f)}</span></div>${nums20(f.predicted20,null,'pending')}<div class="xrayFreezeNote">Источник: ${sourceLabel(f)}. Прогнозные числа зафиксированы и не пересчитываются.</div>${eligibilityHTML(f)}${diagnosticsHTML(f)}</div><div class="xrayFourCombos">${comboPanel('COMBO-5A','c5',f.combo5A||f.combo5||[],'ASC-сборка')}${comboPanel('COMBO-5B','c5b',f.combo5B||[],'Vortex-альтернатива')}${comboPanel('COMBO-7A','c7',f.combo7A||f.combo7||[],'ROOT/LEVEL-сборка')}${comboPanel('COMBO-7B','c7b',f.combo7B||[],'DRAW/Vortex-ветка')}</div>`}
function factBlock(e){if(!e)return '';const h20=e.forecast20Hits||e.layerHits||[];return `<div class="card xrayFactBlock">${head(`Проверка frozen-прогноза на №${e.targetDraw}`,'fact',`Источник: ${sourceLabel(e)} · факт №${e.factDraw}`)}<div class="xrayPanelBody ${panel.fact?'':'hiddenX'}">${eligibilityHTML(e)}<div class="xraySubTitle">Факт целевого тиража №${e.factDraw} · 20 чисел</div>${nums20(e.factBalls, e.factBalls,'fact')}<div class="xraySubTitle">Frozen-прогноз · попаданий ${h20.length}/20</div>${nums20(e.predicted20,h20)}<div class="xrayArchiveCombos">${comboRow('COMBO-5A',e.combo5A||e.combo5||[],e.combo5AHits||e.combo5Hits||[],savedPayout(e,'5A'))}${comboRow('COMBO-5B',e.combo5B||[],e.combo5BHits||[],savedPayout(e,'5B'))}${comboRow('COMBO-7A',e.combo7A||e.combo7||[],e.combo7AHits||e.combo7Hits||[],savedPayout(e,'7A'))}${comboRow('COMBO-7B',e.combo7B||[],e.combo7BHits||[],savedPayout(e,'7B'))}</div><div class="xrayTotalWin">Итого выигрыш: ${money(savedTotal(e))}</div>${diagnosticsHTML(e)}</div></div>`}
function archiveItem(e){const h20=e.forecast20Hits||e.layerHits||[],total=savedTotal(e);return `<div class="xrayArchiveItem"><div class="xrayArchiveTop"><div><b>Проверка frozen на №${e.targetDraw} · ${e.targetDate||'—'} ${e.targetTime||'—'}</b><small>Источник: ${sourceLabel(e)}</small></div><span class="done">проверен</span></div>${eligibilityHTML(e)}<div class="xrayArchiveSection"><b>Факт · 20 чисел</b>${nums20(e.factBalls,e.factBalls,'fact')}</div><div class="xrayArchiveSection"><b>Frozen-прогноз · попаданий ${h20.length}/20</b>${nums20(e.predicted20,h20)}</div><div class="xrayArchiveCombos">${comboRow('5A',e.combo5A||e.combo5||[],e.combo5AHits||e.combo5Hits||[],savedPayout(e,'5A'))}${comboRow('5B',e.combo5B||[],e.combo5BHits||[],savedPayout(e,'5B'))}${comboRow('7A',e.combo7A||e.combo7||[],e.combo7AHits||e.combo7Hits||[],savedPayout(e,'7A'))}${comboRow('7B',e.combo7B||[],e.combo7BHits||[],savedPayout(e,'7B'))}</div><div class="xrayArchiveFoot">Факт: №${e.factDraw} · столб ${e.factColumn||'—'} <strong>Итого: ${money(total)}</strong></div></div>`}
function payoutRows(size){const m=payouts?.combination?.[String(size)]||{};return Object.keys(m).map(Number).sort((a,b)=>a-b).map(h=>`<span><b>${h}/${size}</b> — ${money(m[h])}</span>`).join('')}
function bind(){document.querySelectorAll('[data-xfold]').forEach(b=>b.onclick=()=>{panel[b.dataset.xfold]=!panel[b.dataset.xfold];render()})}
function render(){const root=$('xrayRoot');if(!root)return;if(!runtime){root.innerHTML='<div class="card"><h2>🔬 Рентген структуры</h2><div class="msg">Загружаю SERVER LIVE…</div></div>';return}const f=runtime.forecast,h=runtime.history||[],last=h[0]||null;root.innerHTML=`<div class="card xrayLiveCard"><h2>🔬 Рентген структуры</h2><div class="muted">SERVER LIVE · столбы концентрации · ASC/DRAW · Vortex/Tesla</div>${runtimeNotice()}<div class="xrayLiveLine">ФАКТ ТЕКУЩЕГО ТИРАЖА ${runtime.latestOfficial?`№${runtime.latestOfficial.draw} · ${runtime.latestOfficial.date} ${runtime.latestOfficial.time}`:'—'} · история ${h.length}</div>${nums20(runtime.latestOfficial?.balls||[],null,'fact')}</div><div class="card">${head('Таблица 1–80 · столбы концентрации','grid',f?`Факт источника: ${sourceLabel(f)} → FROZEN на ${targetLabel(f)}`:'ожидаю прогноз')}<div class="xrayPanelBody ${panel.grid?'':'hiddenX'}"><div class="xrayLegend"><span class="current">Факт источника</span><span class="predicted">Следующий frozen-прогноз</span><span class="both">Повтор из факта источника</span><span class="neighbor">Соседняя зона</span></div>${concentrationLabels()}<div id="xrayStage" class="xrayStage"><div class="xrayGrid">${gridHTML(f)}</div><svg id="xrayOverlay" class="xrayOverlay"></svg></div>${structureHTML(f)}</div></div><div class="card">${head('FROZEN-прогноз на следующий тираж','combos',f?`Источник: №${f.sourceDraw} · цель: ${targetLabel(f)}`:'ожидаю SERVER LIVE')}<div class="xrayPanelBody ${panel.combos?'':'hiddenX'}">${forecastBlock(f)}</div></div>${factBlock(last)}<div class="card">${head('История проверенных frozen-прогнозов','archive',`${h.length} записей`)}<div class="xrayPanelBody ${panel.archive?'':'hiddenX'}">${h.length?h.map(archiveItem).join(''):'<div class="xrayEmpty">Пока нет завершённых прогнозов.</div>'}</div></div><div class="card">${head('Таблица выигрышей','payouts',`версия ${payouts?.version||'—'}`)}<div class="xrayPanelBody ${panel.payouts?'':'hiddenX'}"><div class="xrayPayoutCols"><div><b>COMBO-5</b>${payoutRows(5)}</div><div><b>COMBO-7</b>${payoutRows(7)}</div></div></div></div>`;bind();watchLayout();scheduleOverlay()}
async function refresh(){if(refreshing)return refreshing;refreshing=(async()=>{try{const next=await fetchJSON(URL);if(!next||!Array.isArray(next.history)||(!next.forecast&&next.status!=='error')||(next.forecast&&!Array.isArray(next.forecast.predicted20)))throw new Error('Некорректная структура XRAY runtime');await loadPayouts().catch(e=>console.warn('XRAY payouts',e));const stamp=JSON.stringify(next),changed=stamp!==lastGen||!!refreshError;runtime=next;refreshError='';lastGen=stamp;if(changed||!document.querySelector('#xrayRoot .xrayLiveCard'))render();else scheduleOverlay()}catch(e){console.error('XRAY',e);refreshError=String(e.message||e);if(runtime)render();else{const root=$('xrayRoot');if(root)root.innerHTML='<div class="card"><h2>🔬 Рентген структуры</h2>'+runtimeNotice()+'</div>'}}finally{refreshing=null}})();return refreshing}
function notifyDataUpdated(){scheduleOverlay();return refresh()}
window.ComboXrayUI=Object.freeze({refresh,render,notifyDataUpdated,renderOverlay:scheduleOverlay});
for(const event of ['resize','orientationchange','pageshow'])window.addEventListener(event,scheduleOverlay);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)notifyDataUpdated()});
$('xrayRoot')?.addEventListener('toggle',scheduleOverlay,true);
refresh();setInterval(refresh,30000);
})();
