(function(){
'use strict';
const KEY='comboKenoXrayArchiveV1';
let lastAnalysis=null,revealPrediction=false,archiveOpen=false;
const $=id=>document.getElementById(id);
const fmt=n=>String(n).padStart(2,'0');
function draws(){try{return typeof window.getComboDraws==='function'?window.getComboDraws():[]}catch(e){return[]}}
function loadArchive(){try{const a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}}
function saveArchive(a){try{localStorage.setItem(KEY,JSON.stringify(a.slice(0,300)))}catch(e){console.warn('XRAY archive',e)}}
function settleArchive(){const a=loadArchive(),d=draws();let changed=false;for(const e of a){if(e.status==='settled')continue;const fact=d.find(x=>Number(x.draw)===Number(e.targetDraw))||d.find(x=>Number(x.draw)>Number(e.sourceDraw));if(!fact)continue;e.status='settled';e.factDraw=fact.draw;e.factDate=fact.date;e.factTime=fact.time;e.factBalls=[...(fact.balls||[])];const fs=new Set(e.factBalls.map(Number));e.mainHits=(e.main||[]).filter(x=>fs.has(Number(x.n))).map(x=>x.n);e.reserveHits=(e.reserve||[]).filter(x=>fs.has(Number(x.n))).map(x=>x.n);e.settledAt=Date.now();changed=true;}if(changed)saveArchive(a);return a;}
function calibration(){return window.ComboXray?.buildCalibration(settleArchive())||{}}
function scan(){const box=$('xrayMsg');if(box)box.textContent='Читаю архитектуру архива…';requestAnimationFrame(()=>setTimeout(()=>{try{lastAnalysis=window.ComboXray.analyze(draws(),{calibration:calibration()});revealPrediction=false;render();}catch(e){lastAnalysis={ok:false,error:e.message||String(e)};render();}},15));}
function freezeForecast(r){let a=settleArchive();const existing=a.find(x=>Number(x.sourceDraw)===Number(r.sourceDraw));if(existing)return existing;const compact=x=>({n:x.n,confidence:Number(x.confidence.toFixed(4)),source:x.best?.source||null,dr:x.best?.dr??null,dc:x.best?.dc??null,analogDraw:x.best?.analogDraw||null});const e={id:`xr-${r.sourceDraw}-${Date.now()}`,createdAt:Date.now(),version:r.version,sourceDraw:r.sourceDraw,sourceDate:r.sourceDate,sourceTime:r.sourceTime,targetDraw:r.targetDraw,depth:r.depth,signal:r.signal,analogScore:Number(r.analogScore.toFixed(4)),moves:r.moves.slice(0,6).map(m=>({delta:m.delta,weight:Number(m.weight.toFixed(4)),label:m.label})),main:r.main.map(compact),reserve:r.reserve.map(compact),status:'pending'};a.unshift(e);saveArchive(a);return e;}
function showNext(){if(!lastAnalysis?.ok){scan();return}revealPrediction=true;freezeForecast(lastAnalysis);render();}
function toggleArchive(){archiveOpen=!archiveOpen;renderArchive();}
function vectorArrow(dr,dc){if(dr===0&&dc===0)return '●';let s='';if(dr<0&&dc===0)s='↑';else if(dr>0&&dc===0)s='↓';else if(dr===0&&dc>0)s='→';else if(dr===0&&dc<0)s='←';else if(dr<0&&dc>0)s='↗';else if(dr<0&&dc<0)s='↖';else if(dr>0&&dc>0)s='↘';else s='↙';return s;}
function gridHTML(r){const current=draws().at(-1),now=new Set((current?.balls||[]).map(Number)),main=new Set(revealPrediction&&r?.ok?r.main.map(x=>x.n):[]),reserve=new Set(revealPrediction&&r?.ok?r.reserve.map(x=>x.n):[]),sources=new Set(revealPrediction&&r?.ok?[...r.main,...r.reserve].map(x=>x.best?.source).filter(Boolean):[]);return Array.from({length:80},(_,i)=>i+1).map(n=>`<button class="xrayCell ${now.has(n)?'now':''} ${main.has(n)?'main':''} ${reserve.has(n)?'reserve':''} ${sources.has(n)?'source':''}" type="button" data-xcell="${n}" title="Клетка ${n}">${n}</button>`).join('')}
function renderOverlay(r){const svg=$('xrayOverlay'),stage=$('xrayStage');if(!svg||!stage)return;svg.innerHTML='';if(!revealPrediction||!r?.ok)return;const stageRect=stage.getBoundingClientRect();for(const p of [...r.main.map(x=>({...x,kind:'main'})),...r.reserve.map(x=>({...x,kind:'reserve'}))]){const s=stage.querySelector(`[data-xcell="${p.best?.source}"]`),t=stage.querySelector(`[data-xcell="${p.n}"]`);if(!s||!t)continue;const a=s.getBoundingClientRect(),b=t.getBoundingClientRect();const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.left+a.width/2-stageRect.left);line.setAttribute('y1',a.top+a.height/2-stageRect.top);line.setAttribute('x2',b.left+b.width/2-stageRect.left);line.setAttribute('y2',b.top+b.height/2-stageRect.top);if(p.kind==='reserve')line.setAttribute('class','reserve');svg.appendChild(line);}svg.setAttribute('viewBox',`0 0 ${stageRect.width} ${stageRect.height}`);}
function render(){const root=$('xrayRoot');if(!root)return;const r=lastAnalysis,current=draws().at(-1);if(!current){root.innerHTML='<div class="card"><h2>🔬 Рентген</h2><div class="msg">База ещё не загружена.</div></div>';return}const good=r?.ok;root.innerHTML=`<div class="card xrayCard"><h2>🔬 Рентген структуры</h2><div class="muted">Сначала читает рисунок клеток и движение формы. Числа подставляются только на шаге «Ход дальше».</div><div class="xrayToolbar" style="margin-top:9px"><button id="xrayScanBtn" class="primary" type="button">Сканировать</button><button id="xrayNextBtn" type="button" ${good?'':'disabled'}>Ход дальше</button><button id="xrayArchiveBtn" class="ghost" type="button">История Рентгена</button></div><div id="xrayMsg" class="xrayNote">${good?`Источник: №${r.sourceDraw} · ${r.sourceDate} ${r.sourceTime}`:(r?.error||'Нажмите «Сканировать». Глубину Рентген выбирает сам по устойчивости движения.')}</div>${good?`<div class="xrayMeta"><div><b>${r.depth}</b><span>рабочая глубина</span></div><div><b>${r.analogs.length}</b><span>исторических аналогов</span></div><div><b>${r.signal}</b><span>согласованность</span></div></div><div class="xrayStructure"><b>Архитектура движения</b><div class="xrayMoveList">${r.moves.slice(0,5).map(m=>`<span class="xrayMove">${vectorArrow(m.delta[0],m.delta[1])} ${m.label}</span>`).join('')}</div><div class="xrayNote">Это геометрия сетки: строки/позиции и их переходы. Значения 1–80 на этом этапе не участвуют как «частые числа».</div></div>`:''}<div id="xrayStage" class="xrayStage"><div class="xrayGrid">${gridHTML(r)}</div><svg id="xrayOverlay" class="xrayOverlay" aria-hidden="true"></svg></div>${good?`<div class="xrayPrediction ${revealPrediction?'':'hiddenX'}"><b>Ход дальше → следующий тираж №${r.targetDraw}</b><div class="muted" style="margin-top:4px">Основные — до 4 · резерв — до 3. Клетки получены продолжением найденного рисунка.</div><div class="xrayNums">${r.main.map(x=>`<span class="xrayNum main">${fmt(x.n)}</span>`).join('')||'<span class="muted">нет устойчивых основных</span>'}</div><div class="xrayNums">${r.reserve.map(x=>`<span class="xrayNum reserve">${fmt(x.n)}</span>`).join('')||'<span class="muted">резерв не сформирован</span>'}</div><div class="xrayNote">Прогноз при первом открытии «Ход дальше» замораживается в Истории Рентгена и после появления факта не переписывается.</div></div>`:''}</div><div id="xrayArchiveBox" class="card ${archiveOpen?'':'hidden'}"></div>`;
 $('xrayScanBtn')?.addEventListener('click',scan);$('xrayNextBtn')?.addEventListener('click',showNext);$('xrayArchiveBtn')?.addEventListener('click',toggleArchive);if(archiveOpen)renderArchive();requestAnimationFrame(()=>renderOverlay(r));}
function renderArchive(){const box=$('xrayArchiveBox');if(!box)return;const a=settleArchive();box.classList.toggle('hidden',!archiveOpen);if(!archiveOpen)return;box.innerHTML=`<h2>История Рентгена</h2><div class="muted">Только frozen-прогнозы Рентгена. Обычная история комб сюда не попадает.</div>${a.length?a.map(e=>{const settled=e.status==='settled',mh=new Set(e.mainHits||[]),rh=new Set(e.reserveHits||[]);return `<div class="xrayArchiveItem"><div class="xrayArchiveTop"><b>№${e.targetDraw}</b><span>${settled?`факт №${e.factDraw}`:'ожидает факт'}</span></div><div class="muted">XRAY ${e.version} · глубина ${e.depth} · ${e.signal}</div><div class="xrayArchiveNums">Основные: ${(e.main||[]).map(x=>`<span class="${settled?(mh.has(x.n)?'xrayHit':'xrayMiss'):''}">${fmt(x.n)}</span>`).join(' · ')||'—'}<br>Резерв: ${(e.reserve||[]).map(x=>`<span class="${settled?(rh.has(x.n)?'xrayHit':'xrayMiss'):''}">${fmt(x.n)}</span>`).join(' · ')||'—'}${settled?`<br><b>Итог: ${mh.size}/${(e.main||[]).length} основных + ${rh.size}/${(e.reserve||[]).length} резерв</b>`:''}</div></div>`}).join(''):'<div class="xrayEmpty">Архив пока пуст. Запись появится после первого «Ход дальше».</div>'}`;}
function onDataUpdated(){settleArchive();if($('xrayRoot')&&document.getElementById('xray')?.classList.contains('on')){lastAnalysis=null;revealPrediction=false;render();}}
window.ComboXrayUI={render,scan,onDataUpdated,settleArchive};
window.addEventListener('resize',()=>requestAnimationFrame(()=>renderOverlay(lastAnalysis)));
})();
