(function(){
'use strict';
const $=id=>document.getElementById(id),fmt=n=>String(Number(n)).padStart(2,'0'),money=v=>Number(v||0).toLocaleString('ru-RU')+' ₽';
const URL='data/xray-runtime.json';let runtime=null,payouts=null,refreshing=null,refreshError='',lastGen='',panel={grid:true,combos:true,fact:true,archive:false,payouts:false};
let liveSortMode='draw',legendFilter='all';
const responses=new Map();
async function fetchJSON(url){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000),previous=responses.get(url);
 const headers={'Cache-Control':'no-cache'};if(previous?.etag)headers['If-None-Match']=previous.etag;
 try{
  const r=await fetch(url,{cache:'no-store',headers,signal:controller.signal});
  if(r.status===304&&previous)return previous.data;
  if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);
  const data=await r.json();responses.set(url,{etag:r.headers?.get('etag'),data});return data;
 }finally{clearTimeout(timer)}
}
async function loadPayouts(){if(!payouts)payouts=await fetchJSON('keno-payouts-v1.json');return payouts}

const controlStyle=document.createElement('style');
controlStyle.textContent=`
.xrayLiveControls{display:flex;justify-content:flex-end;margin:7px 0 2px}.xrayLiveSortToggle{padding:8px 10px!important;border-radius:9px!important;font-size:11px!important;background:linear-gradient(180deg,#176f9f,#104d70)!important;border-color:#5bc4ff!important;color:#fff!important;touch-action:manipulation}
.xrayLegend{align-items:center}.xrayLegend button[data-xfilter]{display:inline-flex;align-items:center;gap:5px;padding:7px 8px;border:1px solid #315b7d;border-radius:9px;background:#0a1c2d;color:#dceaf4;font-size:9px;cursor:pointer;touch-action:manipulation}.xrayLegend button[data-xfilter]:before{content:"";width:13px;height:13px;border-radius:5px;display:inline-block;border:1px solid #456}.xrayLegend button.current:before{background:linear-gradient(180deg,#45b54f,#207c33);border-color:#6ded7a}.xrayLegend button.predicted:before{background:linear-gradient(180deg,#f1ca36,#b78900);border-color:#ffe45d}.xrayLegend button.both:before{background:linear-gradient(180deg,#b14acb,#753095);border-color:#ef8cff}.xrayLegend button.neighbor:before{background:linear-gradient(180deg,#249ee8,#136ba8);border-color:#69cfff}.xrayLegend button[data-xfilter].selected{border-color:#fff;box-shadow:0 0 0 2px rgba(255,255,255,.17),0 0 10px rgba(91,196,255,.16);color:#fff}.xrayLegend button[data-xfilter].dim{opacity:.42}
@media(max-width:380px){.xrayLiveSortToggle{font-size:10px!important;padding:8px 6px!important}.xrayLegend button[data-xfilter]{font-size:8.6px;padding:6px 5px}}
`;
document.head.appendChild(controlStyle);

function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function savedPayout(e,branch){const legacy=branch==='5A'?'combo5Payout':branch==='7A'?'combo7Payout':null;return Number(e['combo'+branch+'Payout']??(legacy?e[legacy]:0)??0)}
function savedTotal(e){return e.totalPayout!=null?Number(e.totalPayout):['5A','5B','7A','7B'].reduce((s,k)=>s+savedPayout(e,k),0)}
function eligibilityHTML(e){const reasons=[];if(e.lateForecast)reasons.push('создан после времени тиража');if(e.replacedForecast)reasons.push('прогноз заменялся');if(e.statisticsEligible===false&&!reasons.length)reasons.push('время публикации не подтверждено');return reasons.length?'<div class="xrayIntegrityNote">Исключён из честной статистики: '+reasons.join('; ')+'. Результат сохранён для аудита.</div>':''}
function diagnosticsHTML(f){if(!f)return '';return '<details class="xrayDiagnostics"><summary>Данные frozen-прогноза</summary><div>Движок: '+escapeHTML(f.engineVersion||f.version||'—')+'</div><div>Создан: '+escapeHTML(f.createdAt||'—')+'</div><div>Источник: №'+escapeHTML(f.sourceDraw)+' → цель: №'+escapeHTML(f.targetDraw)+'</div><div>Fingerprint: <code>'+escapeHTML(f.forecastFingerprint||'legacy: ещё не присвоен')+'</code></div></details>'}
function runtimeNotice(){const a=runtime?.anomaly;const missing=a?.code==='MISSING_TARGET_FACT',missed=a?.code==='MISSED_FORECAST_WINDOW';const error=a?'<div class="xrayRuntimeError" role="alert"><b>Автоматическое продвижение XRAY остановлено</b><div>'+escapeHTML(a.code)+'</div><div>'+(missing?'В архиве отсутствует целевой факт №'+escapeHTML(a.targetDraw)+'. Frozen-прогноз сохранён.':missed?'Окно создания прогноза пропущено. Требуется проверка истории перед продолжением.':'Требуется проверка runtime.')+'</div></div>':'';return error+(refreshError?'<div class="xrayRuntimeError" role="status">Обновление недоступно. '+(runtime?'Показаны последние успешно загруженные данные. ':'')+escapeHTML(refreshError)+'<div><button type="button" data-xray-retry>Повторить загрузку</button></div></div>':'')}
let overlayFrame=0,resizeObserver=null,visibilityObserver=null;
function scheduleOverlay(){if(overlayFrame)return;overlayFrame=requestAnimationFrame(()=>{overlayFrame=0;renderOverlay(runtime?.forecast)})}
function watchLayout(){resizeObserver?.disconnect();if(typeof ResizeObserver==='function'){resizeObserver??=new ResizeObserver(scheduleOverlay);for(const el of [$('xrayRoot'),$('xrayStage')])if(el)resizeObserver.observe(el)}visibilityObserver?.disconnect();if(typeof MutationObserver==='function'&&$('xray')){visibilityObserver??=new MutationObserver(scheduleOverlay);visibilityObserver.observe($('xray'),{attributes:true,attributeFilter:['class','style','hidden']})}}

function head(title,key,extra=''){return `<div class="xrayPanelHead"><div><b>${title}</b>${extra?`<small>${extra}</small>`:''}</div><button class="xrayFold ${panel[key]?'on':''}" data-xfold="${key}" aria-expanded="${panel[key]}" aria-label="${panel[key]?'Свернуть':'Развернуть'}: ${title}" type="button">${panel[key]?'▼':'▶'}</button></div>`}
function targetLabel(x){return `№${x?.targetDraw||'—'} · ${x?.targetDate||'—'} ${x?.targetTime||'—'}`}
function sourceLabel(x){return `№${x?.sourceDraw||'—'} · ${x?.sourceDate||'—'} ${x?.sourceTime||'—'}${x?.sourceColumn?` · столб ${x.sourceColumn}`:''}`}
function relationClass(s){return String(s||'').toLowerCase().replace('column','root')}
function gridHTML(f){
 const fact=new Set((f?.current20||runtime?.latestOfficial?.balls||[]).map(Number)),pred=new Set((f?.predicted20||[]).map(Number)),nei=new Set((f?.structure?.neighborFront||[]).map(Number));let out='';
 for(let level=0;level<9;level++)for(let c=1;c<=9;c++){const n=level*9+c;if(n>80){out+='<span class="xrayCell blank"></span>';continue}const raw=fact.has(n)&&pred.has(n)?'both':fact.has(n)?'current':pred.has(n)?'predicted':nei.has(n)?'neighbor':'';const cls=legendFilter==='all'||raw===legendFilter?raw:'';out+=`<button class="xrayCell ${cls}" type="button" data-xcell="${n}" title="Ст${c} · L${level}">${n}</button>`}
 return out;
}
function concentrationLabels(){return `<div class="xrayColHeads">${Array.from({length:9},(_,i)=>`<b>Ст${i+1}</b>`).join('')}</div>`}
function transitionEdges(f){
 const current=new Set((f?.current20||[]).map(Number)),predicted=new Set((f?.predicted20||[]).map(Number));
 // Retained purple numbers are support, not FROM -> TO transitions.
 return (f?.movementEdges||[]).filter(e=>{
  const from=Number(e.from),to=Number(e.to);
  return from!==to&&current.has(from)&&!predicted.has(from)&&predicted.has(to)&&!current.has(to);
 }).slice(0,10);
}
function renderOverlay(f){const svg=$('xrayOverlay'),stage=$('xrayStage');if(!svg||!stage)return;svg.replaceChildren();if(!f||legendFilter!=='all')return;const rect=stage.getBoundingClientRect();if(rect.width<=0||rect.height<=0||stage.getClientRects().length===0){svg.removeAttribute('viewBox');return}svg.setAttribute('viewBox',`0 0 ${rect.width} ${rect.height}`);const colors={asc:'#57db77',draw:'#56baff',root:'#ffd34d',vortex:'#d98cff',level:'#ff8e5d'},ns='http://www.w3.org/2000/svg',defs=document.createElementNS(ns,'defs');for(const [type,color] of Object.entries(colors)){const marker=document.createElementNS(ns,'marker'),path=document.createElementNS(ns,'path');for(const [key,value] of Object.entries({id:'xrayArrow-'+type,markerWidth:7,markerHeight:7,refX:6,refY:3.5,orient:'auto'}))marker.setAttribute(key,value);path.setAttribute('d','M0,0 L7,3.5 L0,7 z');path.setAttribute('fill',color);marker.appendChild(path);defs.appendChild(marker)}svg.appendChild(defs);for(const e of transitionEdges(f)){const type=relationClass(e.type);if(!colors[type])continue;const a=stage.querySelector('[data-xcell="'+Number(e.from)+'"]'),b=stage.querySelector('[data-xcell="'+Number(e.to)+'"]');if(!a||!b)continue;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();if(!ar.width||!ar.height||!br.width||!br.height)continue;const line=document.createElementNS(ns,'line');line.setAttribute('x1',ar.left+ar.width/2-rect.left);line.setAttribute('y1',ar.top+ar.height/2-rect.top);line.setAttribute('x2',br.left+br.width/2-rect.left);line.setAttribute('y2',br.top+br.height/2-rect.top);line.setAttribute('class','xrayArrowLine rel-'+type);line.setAttribute('marker-end','url(#xrayArrow-'+type+')');svg.appendChild(line)}}
function activityTable(rows,type){if(!rows?.length)return '';const label=type==='column'?'Ст':'L',key=type==='column'?'column':'level';return `<div class="xrayMoveTableWrap"><table class="xrayMoveTable"><thead><tr><th>${label}</th><th>T1</th><th>T2</th><th>T5</th><th>T10</th><th>T20</th><th>1→2</th><th>2→5</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${label}${r[key]}</th><td>${r.t1}</td><td>${r.t2}</td><td>${r.t5}</td><td>${r.t10}</td><td>${r.t20}</td><td class="${r.d12>0?'up':r.d12<0?'down':''}">${r.d12>0?'+':''}${r.d12}</td><td class="${r.d25>0?'up':r.d25<0?'down':''}">${r.d25>0?'+':''}${r.d25}</td></tr>`).join('')}</tbody></table></div>`}
function structureHTML(f){const s=f?.structure;if(!s)return '';const asc=(s.adjacency?.ascTop||[]).slice(0,7),draw=(s.adjacency?.drawTop||[]).slice(0,7),edges=transitionEdges(f);return `<div class="xrayStructureBox"><div class="xrayStructureTitle"><b>Движение таблицы</b><span>без общего рейтинга · T1/T2/T5/T10/T20</span></div><div class="xrayRankLine"><b>Столбы концентрации:</b> ${(s.columnRank||[]).map(x=>`Ст${x}`).join(' → ')}</div><div class="xrayRankLine"><b>LEVEL:</b> ${(s.levelRank||[]).map(x=>`L${x}`).join(' → ')}</div><details><summary>Активность столбов концентрации</summary>${activityTable(s.concentrationColumns,'column')}</details><details><summary>Активность LEVEL</summary>${activityTable(s.levelRows,'level')}</details><div class="xrayNeighborGrid"><div><b>➡️ По возрастанию ASC</b>${asc.map(x=>`<span>${fmt(x.from)}–${fmt(x.to)} · ${x.strength.toFixed(2)}</span>`).join('')}</div><div><b>🎲 По выпадению DRAW</b>${draw.map(x=>`<span>${fmt(x.from)}→${fmt(x.to)} · ${x.strength.toFixed(2)}</span>`).join('')}</div></div><div class="xrayVortex"><b>Vortex / Tesla:</b> 1→2→4→8→7→5→1 &nbsp; · &nbsp; 3↔6 &nbsp; · &nbsp; 9</div><div class="xrayActualMoves"><b>Связи: только в факте → только в прогнозе</b>${edges.length?edges.map(e=>`<span class="rel-${relationClass(e.type)}">${fmt(e.from)}→${fmt(e.to)} · ${e.type}${e.strength?` ${e.strength.toFixed(2)}`:''}</span>`).join(''):'<small>Нет связей для отображения.</small>'}</div></div>`}
function nums20(nums,hits=null,mode='pending'){const H=hits?new Set(hits.map(Number)):null;return `<div class="xray20Nums">${(nums||[]).map(n=>`<span class="${H?(H.has(Number(n))?'hit':'miss'):mode}">${fmt(n)}</span>`).join('')}</div>`}
function sortedNums(nums,mode){const a=[...(nums||[])];return mode==='asc'?a.map(Number).sort((x,y)=>x-y):a}
function comboRow(label,nums,hits=null,payout=0){const H=hits?new Set(hits.map(Number)):null;return `<div class="xrayComboRow"><b title="${label}">${label.replace('COMBO-','')}</b><div class="xrayComboRowNums">${(nums||[]).map(n=>`<span class="${H?(H.has(Number(n))?'hit':'miss'):'pending'}">${fmt(n)}${H?(H.has(Number(n))?'✓':'×'):''}</span>`).join('')}</div>${H?`<div class="xrayComboResult"><span>${(nums||[]).filter(n=>H.has(Number(n))).length}/${(nums||[]).length} попало</span><strong class="xrayWin">${money(payout)}</strong></div>`:''}</div>`}
function comboPanel(title,cls,nums,subtitle){return `<div class="xrayCombo ${cls}"><div class="xrayComboTop"><b>${title}</b><span>${subtitle}</span></div><div class="xrayComboNums">${(nums||[]).map(n=>`<span>${fmt(n)}</span>`).join('')}</div></div>`}
function forecastBlock(f){if(!f)return '<div class="msg">Жду следующий frozen-прогноз.</div>';return `<div class="xrayForecast20"><div class="xrayForecastTitle"><b>FROZEN-прогноз · 20 чисел</b><span>на ${targetLabel(f)}</span></div>${nums20(f.predicted20,null,'pending')}<div class="xrayFreezeNote">Источник: ${sourceLabel(f)}. Прогнозные числа зафиксированы и не пересчитываются.</div>${eligibilityHTML(f)}${diagnosticsHTML(f)}</div><div class="xrayFourCombos">${comboPanel('COMBO-5A','c5',f.combo5A||f.combo5||[],'ASC-сборка')}${comboPanel('COMBO-5B','c5b',f.combo5B||[],'Vortex-альтернатива')}${comboPanel('COMBO-7A','c7',f.combo7A||f.combo7||[],'ROOT/LEVEL-сборка')}${comboPanel('COMBO-7B','c7b',f.combo7B||[],'DRAW/Vortex-ветка')}</div>`}
function factBlock(e){if(!e)return '';const h20=e.forecast20Hits||e.layerHits||[];return `<div class="card xrayFactBlock">${head(`Проверка frozen-прогноза на №${e.targetDraw}`,'fact',`Источник: ${sourceLabel(e)} · факт №${e.factDraw}`)}<div class="xrayPanelBody ${panel.fact?'':'hiddenX'}">${eligibilityHTML(e)}<div class="xraySubTitle">Факт целевого тиража №${e.factDraw} · 20 чисел</div>${nums20(e.factBalls, e.factBalls,'fact')}<div class="xraySubTitle">Frozen-прогноз · попаданий ${h20.length}/20</div>${nums20(e.predicted20,h20)}<div class="xrayArchiveCombos">${comboRow('COMBO-5A',e.combo5A||e.combo5||[],e.combo5AHits||e.combo5Hits||[],savedPayout(e,'5A'))}${comboRow('COMBO-5B',e.combo5B||[],e.combo5BHits||[],savedPayout(e,'5B'))}${comboRow('COMBO-7A',e.combo7A||e.combo7||[],e.combo7AHits||e.combo7Hits||[],savedPayout(e,'7A'))}${comboRow('COMBO-7B',e.combo7B||[],e.combo7BHits||[],savedPayout(e,'7B'))}</div><div class="xrayTotalWin">Итого выигрыш: ${money(savedTotal(e))}</div>${diagnosticsHTML(e)}</div></div>`}
function archiveItem(e){const h20=e.forecast20Hits||e.layerHits||[],total=savedTotal(e);return `<div class="xrayArchiveItem" data-target="${Number(e.targetDraw||e.factDraw)}"><div class="xrayArchiveTop"><div><b>Проверка frozen на №${e.targetDraw} · ${e.targetDate||'—'} ${e.targetTime||'—'}</b><small>Источник: ${sourceLabel(e)}</small></div><span class="done">проверен</span></div>${eligibilityHTML(e)}<div class="xrayArchiveSection"><b>Факт · 20 чисел</b>${nums20(e.factBalls,e.factBalls,'fact')}</div><div class="xrayArchiveSection"><b>Frozen-прогноз · попаданий ${h20.length}/20</b>${nums20(e.predicted20,h20)}</div><div class="xrayArchiveCombos">${comboRow('5A',e.combo5A||e.combo5||[],e.combo5AHits||e.combo5Hits||[],savedPayout(e,'5A'))}${comboRow('5B',e.combo5B||[],e.combo5BHits||[],savedPayout(e,'5B'))}${comboRow('7A',e.combo7A||e.combo7||[],e.combo7AHits||e.combo7Hits||[],savedPayout(e,'7A'))}${comboRow('7B',e.combo7B||[],e.combo7BHits||[],savedPayout(e,'7B'))}</div><div class="xrayArchiveFoot">Факт: №${e.factDraw} · столб ${e.factColumn||'—'} <strong>Итого: ${money(total)}</strong></div></div>`}
function payoutRows(size){const m=payouts?.combination?.[String(size)]||{};return Object.keys(m).map(Number).sort((a,b)=>a-b).map(h=>`<span><b>${h}/${size}</b> — ${money(m[h])}</span>`).join('')}
const ARCHIVE_PAGE_SIZE=10;
let archivePage=0,hiddenTargets=new Set();
function rendered(){window.dispatchEvent(new Event('combo:xray-render'))}
function visibleHistory(){return (runtime?.history||[]).filter(e=>!hiddenTargets.has(Number(e.targetDraw||e.factDraw)))}
function archiveHTML(){
 const rows=visibleHistory(),pages=Math.max(1,Math.ceil(rows.length/ARCHIVE_PAGE_SIZE));
 archivePage=Math.min(archivePage,pages-1);
 const start=archivePage*ARCHIVE_PAGE_SIZE;
 return `<div class="xrayArchivePager"><button type="button" data-xpage="-1" ${archivePage===0?'disabled':''}>← Новее</button><span>Страница ${archivePage+1} / ${pages}<br>Записи ${rows.length?start+1:0}–${Math.min(start+ARCHIVE_PAGE_SIZE,rows.length)} из ${rows.length}</span><button type="button" data-xpage="1" ${archivePage===pages-1?'disabled':''}>Старее →</button></div>`+(rows.length?rows.slice(start,start+ARCHIVE_PAGE_SIZE).map(archiveItem).join(''):'<div class="xrayEmpty">Нет записей для отображения.</div>');
}
function renderArchive(){const body=$('xrayArchiveBody');if(!body)return;body.innerHTML=panel.archive?archiveHTML():'';bindPages();rendered();scheduleOverlay()}
function bindPages(){document.querySelectorAll('#xrayRoot [data-xpage]').forEach(b=>b.onclick=()=>{archivePage+=Number(b.dataset.xpage);renderArchive();$('xrayArchiveBody')?.scrollIntoView({block:'start'})})}
function setHiddenTargets(values){const next=new Set([...values].map(Number));if(next.size===hiddenTargets.size&&[...next].every(n=>hiddenTargets.has(n)))return;hiddenTargets=next;renderArchive()}
function bind(){document.querySelectorAll('#xrayRoot [data-xfold]').forEach(b=>b.onclick=()=>{
 const key=b.dataset.xfold;panel[key]=!panel[key];
 b.classList.toggle('on',panel[key]);b.setAttribute('aria-expanded',String(panel[key]));b.setAttribute('aria-label',(panel[key]?'Свернуть':'Развернуть')+': '+b.closest('.xrayPanelHead').querySelector('b').textContent);b.textContent=panel[key]?'▼':'▶';
 b.closest('.card').querySelector('.xrayPanelBody').classList.toggle('hiddenX',!panel[key]);
 if(key==='archive')renderArchive();scheduleOverlay();
});bindPages();
document.querySelectorAll('#xrayRoot [data-xfilter]').forEach(b=>b.onclick=()=>{const key=b.dataset.xfilter;legendFilter=legendFilter===key?'all':key;render()});
const live=$('xrayRoot')?.querySelector('[data-xlive-sort]');if(live)live.onclick=()=>{liveSortMode=liveSortMode==='asc'?'draw':'asc';render()}}

function render(){const root=$('xrayRoot');if(!root)return;if(!runtime){root.innerHTML='<div class="card"><h2>🔬 Рентген структуры</h2><div class="msg">Загружаю SERVER LIVE…</div></div>';return}const f=runtime.forecast,h=runtime.history||[],last=h[0]||null;root.innerHTML=`<div class="card xrayLiveCard"><h2>🔬 Рентген структуры</h2><div class="muted">SERVER LIVE · столбы концентрации · ASC/DRAW · Vortex/Tesla</div>${runtimeNotice()}<div class="xrayLiveControls"><button type="button" class="xrayLiveSortToggle" data-xlive-sort>${liveSortMode==='asc'?'➡️ По возрастанию':'🎲 По выпадению'}</button></div><div class="xrayLiveLine">ФАКТ ТЕКУЩЕГО ТИРАЖА ${runtime.latestOfficial?`№${runtime.latestOfficial.draw} · ${runtime.latestOfficial.date} ${runtime.latestOfficial.time}`:'—'} · история ${h.length}</div>${nums20(sortedNums(runtime.latestOfficial?.balls||[],liveSortMode),null,'fact')}</div><div class="card">${head('Таблица 1–80 · столбы концентрации','grid',f?`Факт источника: ${sourceLabel(f)} → FROZEN на ${targetLabel(f)}`:'ожидаю прогноз')}<div class="xrayPanelBody ${panel.grid?'':'hiddenX'}"><div class="xrayLegend"><button type="button" data-xfilter="current" class="current ${legendFilter==='current'?'selected':legendFilter!=='all'?'dim':''}">Факт источника</button><button type="button" data-xfilter="predicted" class="predicted ${legendFilter==='predicted'?'selected':legendFilter!=='all'?'dim':''}">Следующий frozen-прогноз</button><button type="button" data-xfilter="both" class="both ${legendFilter==='both'?'selected':legendFilter!=='all'?'dim':''}">Повтор из факта источника</button><button type="button" data-xfilter="neighbor" class="neighbor ${legendFilter==='neighbor'?'selected':legendFilter!=='all'?'dim':''}">Соседняя зона</button></div>${concentrationLabels()}<div id="xrayStage" class="xrayStage"><div class="xrayGrid">${gridHTML(f)}</div><svg id="xrayOverlay" class="xrayOverlay"></svg></div>${structureHTML(f)}</div></div><div class="card">${head('FROZEN-прогноз на следующий тираж','combos',f?`Источник: №${f.sourceDraw} · цель: ${targetLabel(f)}`:'ожидаю SERVER LIVE')}<div class="xrayPanelBody ${panel.combos?'':'hiddenX'}">${forecastBlock(f)}</div></div>${factBlock(last)}<div class="card">${head('История проверенных frozen-прогнозов','archive',`${h.length} записей`)}<div id="xrayArchiveBody" class="xrayPanelBody ${panel.archive?'':'hiddenX'}">${panel.archive?archiveHTML():''}</div></div><div class="card">${head('Таблица выигрышей','payouts',`версия ${payouts?.version||'—'}`)}<div class="xrayPanelBody ${panel.payouts?'':'hiddenX'}"><div class="xrayPayoutCols"><div><b>COMBO-5</b>${payoutRows(5)}</div><div><b>COMBO-7</b>${payoutRows(7)}</div></div></div></div>`;bind();watchLayout();scheduleOverlay();rendered()}
function xrayActive(){return !!$('xray')?.classList?.contains('on')}
async function refresh(force=true){if(!force&&!xrayActive())return runtime;if(refreshing)return refreshing;refreshing=(async()=>{try{const next=await fetchJSON(URL);if(!next||!Array.isArray(next.history)||(!next.forecast&&next.status!=='error')||(next.forecast&&!Array.isArray(next.forecast.predicted20)))throw new Error('Некорректная структура XRAY runtime');await loadPayouts().catch(e=>console.warn('XRAY payouts',e));const stamp=/^[a-f0-9]{64}$/.test(next.generation||'')?next.generation:JSON.stringify(next),changed=stamp!==lastGen||!!refreshError;runtime=next;refreshError='';lastGen=stamp;if(changed||!document.querySelector('#xrayRoot .xrayLiveCard'))render();else scheduleOverlay()}catch(e){console.error('XRAY',e);refreshError=String(e.message||e);if(runtime)render();else{const root=$('xrayRoot');if(root)root.innerHTML='<div class="card"><h2>🔬 Рентген структуры</h2>'+runtimeNotice()+'</div>'}}finally{refreshing=null}})();return refreshing}
function notifyDataUpdated(){scheduleOverlay();return refresh(false)}
window.ComboXrayUI=Object.freeze({refresh,render,notifyDataUpdated,renderOverlay:scheduleOverlay,getRuntime:()=>runtime,getPayouts:()=>payouts,setHiddenTargets});
for(const event of ['resize','orientationchange','pageshow'])window.addEventListener(event,scheduleOverlay);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&xrayActive())notifyDataUpdated()});
$('xrayRoot')?.addEventListener('toggle',scheduleOverlay,true);
$('xrayRoot')?.addEventListener('click',e=>{const button=e.target.closest('[data-xray-retry]');if(button){button.disabled=true;button.textContent='Загрузка…';refresh().finally(()=>{button.disabled=false;button.textContent='Повторить загрузку'})}});
refresh(false);setInterval(()=>{if(!document.hidden&&xrayActive())refresh(false)},30000);
})();